//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SIRA_Notificaciones.wsSiraGuias {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'PolicyReference' del espacio de nombres 'http://www.w3.org/ns/ws-policy'.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConsultaetalleManifestPortBinding", Namespace="http://ws.consultadetallemanifiestos.recintos.www.ventanillaunica.gob.mx")]
    public partial class ConsultaetalleManifestService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback notificacionIngresoMercanciaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConsultaetalleManifestService() {
            this.Url = global::SIRA_Notificaciones.Properties.Settings.Default.SIRA_Notificaciones_wsSiraGuias_ConsultaetalleManifestService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event notificacionIngresoMercanciaCompletedEventHandler notificacionIngresoMercanciaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.consultadetallemanifiestos.recintos.www.ventanillaunica.gob.mx", ResponseNamespace="http://ws.consultadetallemanifiestos.recintos.www.ventanillaunica.gob.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public manifiestoDetalleResponse notificacionIngresoMercancia([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] manifiestoDetalleRequest arg0) {
            object[] results = this.Invoke("notificacionIngresoMercancia", new object[] {
                        arg0});
            return ((manifiestoDetalleResponse)(results[0]));
        }
        
        /// <remarks/>
        public void notificacionIngresoMercanciaAsync(manifiestoDetalleRequest arg0) {
            this.notificacionIngresoMercanciaAsync(arg0, null);
        }
        
        /// <remarks/>
        public void notificacionIngresoMercanciaAsync(manifiestoDetalleRequest arg0, object userState) {
            if ((this.notificacionIngresoMercanciaOperationCompleted == null)) {
                this.notificacionIngresoMercanciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnotificacionIngresoMercanciaOperationCompleted);
            }
            this.InvokeAsync("notificacionIngresoMercancia", new object[] {
                        arg0}, this.notificacionIngresoMercanciaOperationCompleted, userState);
        }
        
        private void OnnotificacionIngresoMercanciaOperationCompleted(object arg) {
            if ((this.notificacionIngresoMercanciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.notificacionIngresoMercanciaCompleted(this, new notificacionIngresoMercanciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultadetallemanifiestos.recintos.www.ventanillaunica.gob.mx")]
    public partial class manifiestoDetalleRequest {
        
        private string camirField;
        
        private string traficoField;
        
        private string manifiestoField;
        
        private string guiaMasterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string camir {
            get {
                return this.camirField;
            }
            set {
                this.camirField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string trafico {
            get {
                return this.traficoField;
            }
            set {
                this.traficoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string manifiesto {
            get {
                return this.manifiestoField;
            }
            set {
                this.manifiestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string guiaMaster {
            get {
                return this.guiaMasterField;
            }
            set {
                this.guiaMasterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultadetallemanifiestos.recintos.www.ventanillaunica.gob.mx")]
    public partial class InformacionDeSellos {
        
        private string candadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string candado {
            get {
                return this.candadoField;
            }
            set {
                this.candadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultadetallemanifiestos.recintos.www.ventanillaunica.gob.mx")]
    public partial class InformacionContenedor {
        
        private string inicialesField;
        
        private string numeroField;
        
        private string tipoField;
        
        private string estadoField;
        
        private InformacionDeSellos[] selloField;
        
        private InformacionDeMercancia[] mercanciaField;
        
        private InformacionDePersonas[] personasField;
        
        private InformacionGuiaHouse[] guiaHouseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string iniciales {
            get {
                return this.inicialesField;
            }
            set {
                this.inicialesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sello", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public InformacionDeSellos[] sello {
            get {
                return this.selloField;
            }
            set {
                this.selloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mercancia", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public InformacionDeMercancia[] mercancia {
            get {
                return this.mercanciaField;
            }
            set {
                this.mercanciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("personas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public InformacionDePersonas[] personas {
            get {
                return this.personasField;
            }
            set {
                this.personasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("guiaHouse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public InformacionGuiaHouse[] guiaHouse {
            get {
                return this.guiaHouseField;
            }
            set {
                this.guiaHouseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultadetallemanifiestos.recintos.www.ventanillaunica.gob.mx")]
    public partial class InformacionDeMercancia {
        
        private long secuenciaField;
        
        private bool secuenciaFieldSpecified;
        
        private string paisField;
        
        private string descripcionField;
        
        private double valorField;
        
        private bool valorFieldSpecified;
        
        private string monedaField;
        
        private double cantidadField;
        
        private bool cantidadFieldSpecified;
        
        private string umcField;
        
        private double pesoField;
        
        private bool pesoFieldSpecified;
        
        private string umpField;
        
        private double volumenField;
        
        private bool volumenFieldSpecified;
        
        private string observacionesField;
        
        private InformacionDeVin[] vinField;
        
        private InformacionDeImo[] imoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long secuencia {
            get {
                return this.secuenciaField;
            }
            set {
                this.secuenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secuenciaSpecified {
            get {
                return this.secuenciaFieldSpecified;
            }
            set {
                this.secuenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorSpecified {
            get {
                return this.valorFieldSpecified;
            }
            set {
                this.valorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSpecified {
            get {
                return this.cantidadFieldSpecified;
            }
            set {
                this.cantidadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string umc {
            get {
                return this.umcField;
            }
            set {
                this.umcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double peso {
            get {
                return this.pesoField;
            }
            set {
                this.pesoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pesoSpecified {
            get {
                return this.pesoFieldSpecified;
            }
            set {
                this.pesoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ump {
            get {
                return this.umpField;
            }
            set {
                this.umpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double volumen {
            get {
                return this.volumenField;
            }
            set {
                this.volumenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool volumenSpecified {
            get {
                return this.volumenFieldSpecified;
            }
            set {
                this.volumenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vin", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public InformacionDeVin[] vin {
            get {
                return this.vinField;
            }
            set {
                this.vinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("imo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public InformacionDeImo[] imo {
            get {
                return this.imoField;
            }
            set {
                this.imoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultadetallemanifiestos.recintos.www.ventanillaunica.gob.mx")]
    public partial class InformacionDeVin {
        
        private string vinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vin {
            get {
                return this.vinField;
            }
            set {
                this.vinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultadetallemanifiestos.recintos.www.ventanillaunica.gob.mx")]
    public partial class InformacionDeImo {
        
        private string imoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string imo {
            get {
                return this.imoField;
            }
            set {
                this.imoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultadetallemanifiestos.recintos.www.ventanillaunica.gob.mx")]
    public partial class InformacionDePersonas {
        
        private string tipoPersonaField;
        
        private string nombreField;
        
        private string calleDomicilioField;
        
        private string numeroInteriorField;
        
        private string numeroExteriorField;
        
        private string cpField;
        
        private string municipioField;
        
        private string entidadFederativaField;
        
        private string paisField;
        
        private string rfcOTaxIdField;
        
        private string correoElectronicoField;
        
        private string ciudadField;
        
        private string contactoField;
        
        private long telefonoField;
        
        private bool telefonoFieldSpecified;
        
        private string correoContactoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoPersona {
            get {
                return this.tipoPersonaField;
            }
            set {
                this.tipoPersonaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string calleDomicilio {
            get {
                return this.calleDomicilioField;
            }
            set {
                this.calleDomicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroInterior {
            get {
                return this.numeroInteriorField;
            }
            set {
                this.numeroInteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroExterior {
            get {
                return this.numeroExteriorField;
            }
            set {
                this.numeroExteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cp {
            get {
                return this.cpField;
            }
            set {
                this.cpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string municipio {
            get {
                return this.municipioField;
            }
            set {
                this.municipioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string entidadFederativa {
            get {
                return this.entidadFederativaField;
            }
            set {
                this.entidadFederativaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rfcOTaxId {
            get {
                return this.rfcOTaxIdField;
            }
            set {
                this.rfcOTaxIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contacto {
            get {
                return this.contactoField;
            }
            set {
                this.contactoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool telefonoSpecified {
            get {
                return this.telefonoFieldSpecified;
            }
            set {
                this.telefonoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correoContacto {
            get {
                return this.correoContactoField;
            }
            set {
                this.correoContactoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultadetallemanifiestos.recintos.www.ventanillaunica.gob.mx")]
    public partial class InformacionGuiaHouse {
        
        private string numeroGuiaBlField;
        
        private string caatField;
        
        private long tipoOperacionField;
        
        private bool tipoOperacionFieldSpecified;
        
        private double valorDeclaradoField;
        
        private bool valorDeclaradoFieldSpecified;
        
        private string monedaField;
        
        private double pesoField;
        
        private bool pesoFieldSpecified;
        
        private string umpField;
        
        private double volumenField;
        
        private bool volumenFieldSpecified;
        
        private string umvField;
        
        private double piezasField;
        
        private bool piezasFieldSpecified;
        
        private string idParcialidadField;
        
        private long secuenciaField;
        
        private bool secuenciaFieldSpecified;
        
        private string observacionesField;
        
        private InformacionDeMercancia[] mercanciaField;
        
        private InformacionDePersonas[] personasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroGuiaBl {
            get {
                return this.numeroGuiaBlField;
            }
            set {
                this.numeroGuiaBlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string caat {
            get {
                return this.caatField;
            }
            set {
                this.caatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long tipoOperacion {
            get {
                return this.tipoOperacionField;
            }
            set {
                this.tipoOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoOperacionSpecified {
            get {
                return this.tipoOperacionFieldSpecified;
            }
            set {
                this.tipoOperacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double valorDeclarado {
            get {
                return this.valorDeclaradoField;
            }
            set {
                this.valorDeclaradoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorDeclaradoSpecified {
            get {
                return this.valorDeclaradoFieldSpecified;
            }
            set {
                this.valorDeclaradoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double peso {
            get {
                return this.pesoField;
            }
            set {
                this.pesoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pesoSpecified {
            get {
                return this.pesoFieldSpecified;
            }
            set {
                this.pesoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ump {
            get {
                return this.umpField;
            }
            set {
                this.umpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double volumen {
            get {
                return this.volumenField;
            }
            set {
                this.volumenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool volumenSpecified {
            get {
                return this.volumenFieldSpecified;
            }
            set {
                this.volumenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string umv {
            get {
                return this.umvField;
            }
            set {
                this.umvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double piezas {
            get {
                return this.piezasField;
            }
            set {
                this.piezasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool piezasSpecified {
            get {
                return this.piezasFieldSpecified;
            }
            set {
                this.piezasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idParcialidad {
            get {
                return this.idParcialidadField;
            }
            set {
                this.idParcialidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long secuencia {
            get {
                return this.secuenciaField;
            }
            set {
                this.secuenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secuenciaSpecified {
            get {
                return this.secuenciaFieldSpecified;
            }
            set {
                this.secuenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mercancia", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public InformacionDeMercancia[] mercancia {
            get {
                return this.mercanciaField;
            }
            set {
                this.mercanciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("personas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public InformacionDePersonas[] personas {
            get {
                return this.personasField;
            }
            set {
                this.personasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultadetallemanifiestos.recintos.www.ventanillaunica.gob.mx")]
    public partial class InformacionBlMaster {
        
        private string numeroGuiaBlField;
        
        private string caatField;
        
        private long tipoOperacionField;
        
        private bool tipoOperacionFieldSpecified;
        
        private double valorDeclaradoField;
        
        private bool valorDeclaradoFieldSpecified;
        
        private string monedaField;
        
        private double pesoField;
        
        private bool pesoFieldSpecified;
        
        private string umpField;
        
        private double volumenField;
        
        private bool volumenFieldSpecified;
        
        private string umvField;
        
        private double piezasField;
        
        private bool piezasFieldSpecified;
        
        private string idParcialidadField;
        
        private long secuenciaField;
        
        private bool secuenciaFieldSpecified;
        
        private string observacionesField;
        
        private InformacionDeMercancia[] mercanciaField;
        
        private InformacionDePersonas[] personasField;
        
        private InformacionGuiaHouse[] guiaHouseField;
        
        private InformacionContenedor[] contenedorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroGuiaBl {
            get {
                return this.numeroGuiaBlField;
            }
            set {
                this.numeroGuiaBlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string caat {
            get {
                return this.caatField;
            }
            set {
                this.caatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long tipoOperacion {
            get {
                return this.tipoOperacionField;
            }
            set {
                this.tipoOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoOperacionSpecified {
            get {
                return this.tipoOperacionFieldSpecified;
            }
            set {
                this.tipoOperacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double valorDeclarado {
            get {
                return this.valorDeclaradoField;
            }
            set {
                this.valorDeclaradoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorDeclaradoSpecified {
            get {
                return this.valorDeclaradoFieldSpecified;
            }
            set {
                this.valorDeclaradoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double peso {
            get {
                return this.pesoField;
            }
            set {
                this.pesoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pesoSpecified {
            get {
                return this.pesoFieldSpecified;
            }
            set {
                this.pesoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ump {
            get {
                return this.umpField;
            }
            set {
                this.umpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double volumen {
            get {
                return this.volumenField;
            }
            set {
                this.volumenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool volumenSpecified {
            get {
                return this.volumenFieldSpecified;
            }
            set {
                this.volumenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string umv {
            get {
                return this.umvField;
            }
            set {
                this.umvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double piezas {
            get {
                return this.piezasField;
            }
            set {
                this.piezasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool piezasSpecified {
            get {
                return this.piezasFieldSpecified;
            }
            set {
                this.piezasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idParcialidad {
            get {
                return this.idParcialidadField;
            }
            set {
                this.idParcialidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long secuencia {
            get {
                return this.secuenciaField;
            }
            set {
                this.secuenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secuenciaSpecified {
            get {
                return this.secuenciaFieldSpecified;
            }
            set {
                this.secuenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mercancia", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public InformacionDeMercancia[] mercancia {
            get {
                return this.mercanciaField;
            }
            set {
                this.mercanciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("personas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public InformacionDePersonas[] personas {
            get {
                return this.personasField;
            }
            set {
                this.personasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("guiaHouse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public InformacionGuiaHouse[] guiaHouse {
            get {
                return this.guiaHouseField;
            }
            set {
                this.guiaHouseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contenedor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public InformacionContenedor[] contenedor {
            get {
                return this.contenedorField;
            }
            set {
                this.contenedorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultadetallemanifiestos.recintos.www.ventanillaunica.gob.mx")]
    public partial class InformacionDeTransporte {
        
        private string numeroVueloBuqueViajeImoField;
        
        private string tipoTransporteField;
        
        private System.DateTime fechaHoraDeArriboField;
        
        private bool fechaHoraDeArriboFieldSpecified;
        
        private string origenVueloBuqueField;
        
        private string numeroManifiestoField;
        
        private string caatField;
        
        private double pesoField;
        
        private bool pesoFieldSpecified;
        
        private string umpField;
        
        private double piezasField;
        
        private bool piezasFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroVueloBuqueViajeImo {
            get {
                return this.numeroVueloBuqueViajeImoField;
            }
            set {
                this.numeroVueloBuqueViajeImoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoTransporte {
            get {
                return this.tipoTransporteField;
            }
            set {
                this.tipoTransporteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaHoraDeArribo {
            get {
                return this.fechaHoraDeArriboField;
            }
            set {
                this.fechaHoraDeArriboField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaHoraDeArriboSpecified {
            get {
                return this.fechaHoraDeArriboFieldSpecified;
            }
            set {
                this.fechaHoraDeArriboFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string origenVueloBuque {
            get {
                return this.origenVueloBuqueField;
            }
            set {
                this.origenVueloBuqueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroManifiesto {
            get {
                return this.numeroManifiestoField;
            }
            set {
                this.numeroManifiestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string caat {
            get {
                return this.caatField;
            }
            set {
                this.caatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double peso {
            get {
                return this.pesoField;
            }
            set {
                this.pesoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pesoSpecified {
            get {
                return this.pesoFieldSpecified;
            }
            set {
                this.pesoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ump {
            get {
                return this.umpField;
            }
            set {
                this.umpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double piezas {
            get {
                return this.piezasField;
            }
            set {
                this.piezasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool piezasSpecified {
            get {
                return this.piezasFieldSpecified;
            }
            set {
                this.piezasFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultadetallemanifiestos.recintos.www.ventanillaunica.gob.mx")]
    public partial class InformacionOperacionGeneral {
        
        private string consecutivoField;
        
        private string ideAsociadoField;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private long tipoMovimientoField;
        
        private bool tipoMovimientoFieldSpecified;
        
        private long detalleMovimientoField;
        
        private bool detalleMovimientoFieldSpecified;
        
        private long tipoOperacionField;
        
        private bool tipoOperacionFieldSpecified;
        
        private string cveRecintoFiscalizadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consecutivo {
            get {
                return this.consecutivoField;
            }
            set {
                this.consecutivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ideAsociado {
            get {
                return this.ideAsociadoField;
            }
            set {
                this.ideAsociadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long tipoMovimiento {
            get {
                return this.tipoMovimientoField;
            }
            set {
                this.tipoMovimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoMovimientoSpecified {
            get {
                return this.tipoMovimientoFieldSpecified;
            }
            set {
                this.tipoMovimientoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long detalleMovimiento {
            get {
                return this.detalleMovimientoField;
            }
            set {
                this.detalleMovimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool detalleMovimientoSpecified {
            get {
                return this.detalleMovimientoFieldSpecified;
            }
            set {
                this.detalleMovimientoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long tipoOperacion {
            get {
                return this.tipoOperacionField;
            }
            set {
                this.tipoOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoOperacionSpecified {
            get {
                return this.tipoOperacionFieldSpecified;
            }
            set {
                this.tipoOperacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cveRecintoFiscalizado {
            get {
                return this.cveRecintoFiscalizadoField;
            }
            set {
                this.cveRecintoFiscalizadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultadetallemanifiestos.recintos.www.ventanillaunica.gob.mx")]
    public partial class manifiestoDetalleResponse {
        
        private InformacionOperacionGeneral informacionGeneralField;
        
        private InformacionDeTransporte transporteField;
        
        private InformacionBlMaster guiaMasterField;
        
        private string[] mensajesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InformacionOperacionGeneral informacionGeneral {
            get {
                return this.informacionGeneralField;
            }
            set {
                this.informacionGeneralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InformacionDeTransporte transporte {
            get {
                return this.transporteField;
            }
            set {
                this.transporteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InformacionBlMaster guiaMaster {
            get {
                return this.guiaMasterField;
            }
            set {
                this.guiaMasterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] mensajes {
            get {
                return this.mensajesField;
            }
            set {
                this.mensajesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void notificacionIngresoMercanciaCompletedEventHandler(object sender, notificacionIngresoMercanciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class notificacionIngresoMercanciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal notificacionIngresoMercanciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public manifiestoDetalleResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((manifiestoDetalleResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591